services:
    backend:
        restart: always
        build:
            context: ./app/
            dockerfile: Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        volumes:
            - ./app:/usr/src/app/
        networks:
            - app_network
        depends_on:
            - db
    db:
        image: postgres:14.5
        env_file:
            - ./.env.dev.db
        volumes:
            - db_data:/var/lib/postgresql/data/
        networks:
            - app_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 3s
            timeout: 5s
            retries: 5

volumes:
    db_data:

networks:
    app_network:
